[build]
builder = "Nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[build.env]
PHP_VERSION = "7.4"

[databases]
cityhall = { database = "cityhall", sql = "./database/migrations" }
